/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:96b62544-378f-41f0-b82f-08bccdee7499",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lXGOWZAD5",
    "aws_user_pools_web_client_id": "57q2fd729pji09r62n636ve1fj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "Cognito": {
            "region": "us-east-1",
            "userPoolId": "us-east-1_mld8IjN9e",
            "userPoolWebClientId": "229bq6q1fbjtp0r43hhoq5qoe7",
            "authenticationFlowType": "USER_PASSWORD_AUTH"
        }
    }
};


export default awsmobile;
